import { NextResponse } from "next/server";
import { logAdminAuditEvent, requireAdmin, supabaseAdmin } from "@/lib/admin-api";

type InboxType = "community_post" | "source_suggestion" | "hallucination_report" | "report" | "topic_suggestion" | "topic_candidate";
type InboxItem = { id:string; type:InboxType; risk:string; status?:string|null; created_at?:string|null; contributor_hash?:string|null; document_id?:string|null; document_title?:string|null; document_slug?:string|null; document_lang?:string|null; claim_id?:string|null; title:string; summary?:string|null; url?:string|null; actions:string[] };
type SupabaseAdminClient = NonNullable<ReturnType<typeof supabaseAdmin>>;
type AnyRow = Record<string, unknown>;
function objectValue(value: unknown): AnyRow | null { return value && typeof value === "object" && !Array.isArray(value) ? value as AnyRow : null; }
const ACTIONS = ["approve", "reject", "spam", "promote_to_source", "create_topic_candidate", "link_to_claim"];
const HIGH = new Set(["high", "forbidden"]);
function text(v: unknown) { return typeof v === "string" ? v : v == null ? null : String(v); }
function created(row: AnyRow) { return text(row.created_at ?? row.submitted_at ?? row.updated_at); }
function risk(row: AnyRow, fallback = "medium") { const value = text(row.risk_tier ?? row.risk ?? row.category)?.toLowerCase(); if (!value) return fallback; if (HIGH.has(value) || /finance|health|medical|legal|bank|insurance|realtime|spam|abuse/.test(value)) return "high"; return value.includes("low") ? "low" : "medium"; }
function docFrom(row: AnyRow) { const doc = objectValue(Array.isArray(row.documents) ? row.documents[0] : row.documents); const claim = objectValue(row.claims); return { document_id: text(row.document_id ?? claim?.document_id), document_title: text(doc?.title), document_slug: text(doc?.slug), document_lang: text(doc?.lang) }; }
function mapRow(type: InboxType, row: AnyRow): InboxItem { const base = { id: String(row.id), type, risk: risk(row), status: text(row.status), created_at: created(row), contributor_hash: text(row.contributor_hash), ...docFrom(row) };
  if (type === "community_post") return { ...base, title: `${row.author_type ?? "user"}: ${row.author_name ?? "익명"}`, summary: text(row.content), actions: ["approve", "reject", "spam", "create_topic_candidate"] };
  if (type === "source_suggestion") return { ...base, claim_id: text(row.claim_id ?? objectValue(row.claims)?.id), title: text(row.title) ?? text(row.url) ?? "Source suggestion", summary: text(row.citation ?? row.description), url: text(row.url), actions: ["approve", "reject", "spam", "promote_to_source", "link_to_claim"] };
  if (type === "hallucination_report") return { ...base, claim_id: text(row.claim_id), title: `${row.ai_service ?? "AI"} hallucination`, summary: text(row.expected_correction ?? row.ai_answer ?? row.prompt), actions: ["approve", "reject", "spam", "create_topic_candidate", "link_to_claim"] };
  if (type === "report") return { ...base, title: `${row.report_type ?? "correction"} report`, summary: text(row.message), actions: ["approve", "reject", "spam", "create_topic_candidate", "link_to_claim"] };
  if (type === "topic_suggestion") return { ...base, title: text(row.question) ?? "Topic suggestion", summary: text(row.reason), url: text(row.source_url ?? row.related_url), actions: ["approve", "reject", "spam", "create_topic_candidate"] };
  return { ...base, title: text(row.title) ?? "Topic candidate", summary: text(row.why_people_ask_ai ?? row.why_ai_gets_wrong), actions: ["approve", "reject", "spam"] };
}
async function list(sb: SupabaseAdminClient, type: InboxType, table: string, select: string, statuses: string[], limit: number) { try { const { data, error } = await sb.from(table).select(select).in("status", statuses).order(type === "topic_suggestion" ? "submitted_at" : "created_at", { ascending: false }).limit(limit); if (error) throw error; return { items: (data ?? []).map((row: AnyRow) => mapRow(type, row)), error: null }; } catch (error) { return { items: [] as InboxItem[], error: `${table}: ${error instanceof Error ? error.message : String(error)}` }; } }
export async function GET(request: Request) { const adminError = await requireAdmin(request, "admin.inbox.read"); if (adminError) return adminError; const sb = supabaseAdmin(); if (!sb) return NextResponse.json({ error: "SUPABASE_SERVICE_ROLE_KEY not configured" }, { status: 500 }); const url = new URL(request.url); const limit = Math.min(Number(url.searchParams.get("limit") ?? 30), 100); const results = await Promise.all([ list(sb, "community_post", "community_posts", "*, documents(id,title,slug,lang)", ["pending", "published"], limit), list(sb, "source_suggestion", "source_suggestions", "*, claims(id,document_id,entity_id)", ["pending", "new"], limit), list(sb, "hallucination_report", "hallucination_reports", "*, documents(id,title,slug,lang)", ["new", "reviewing"], limit), list(sb, "report", "reports", "*, documents(id,title,slug,lang)", ["new", "reviewing"], limit), list(sb, "topic_suggestion", "topic_suggestions", "*", ["new", "spam_suspected"], limit), list(sb, "topic_candidate", "topic_candidates", "*", ["new", "reviewing", "approved", "spam_suspected"], limit) ]); const items = results.flatMap((r) => r.items).sort((a, b) => Date.parse(b.created_at ?? "0") - Date.parse(a.created_at ?? "0")); await logAdminAuditEvent(sb, request, "admin.inbox.read", { count: items.length }); return NextResponse.json({ items, errors: results.map((r) => r.error).filter(Boolean), actions: ACTIONS }); }
function tableFor(type: string) { return ({ community_post:"community_posts", source_suggestion:"source_suggestions", hallucination_report:"hallucination_reports", report:"reports", topic_suggestion:"topic_suggestions", topic_candidate:"topic_candidates" } as Record<string,string>)[type]; }
function statusFor(type: string, action: string) { if (action === "spam") return "spam"; if (action === "reject") return "rejected"; if (action === "approve") return type === "community_post" ? "published" : type === "source_suggestion" || type === "hallucination_report" ? "accepted" : type === "topic_candidate" ? "approved" : "reviewing"; return null; }
export async function PATCH(request: Request) { const adminError = await requireAdmin(request, "admin.inbox.update"); if (adminError) return adminError; const sb = supabaseAdmin(); if (!sb) return NextResponse.json({ error: "SUPABASE_SERVICE_ROLE_KEY not configured" }, { status: 500 }); const body = await request.json(); const id = String(body.id ?? "").trim(); const type = String(body.type ?? "").trim(); const action = String(body.action ?? "").trim(); if (!id || !tableFor(type) || !ACTIONS.includes(action)) return NextResponse.json({ error: "valid id, type, and action are required" }, { status: 400 });
  if (action === "promote_to_source") { const { data: s, error: fetchError } = await sb.from("source_suggestions").select("*").eq("id", id).single(); if (fetchError || !s?.claim_id) return NextResponse.json({ error: "source suggestion with claim_id required" }, { status: 400 }); const sourceId = `src-${s.claim_id}-${Date.now()}`; const { error } = await sb.from("claim_sources").insert({ id: sourceId, claim_id: s.claim_id, source_type: s.source_type ?? "web", title: s.title ?? s.url ?? "Suggested source", url: s.url, citation: s.citation, contributor_hash: s.contributor_hash, observed_at: new Date().toISOString() }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); await sb.from("source_suggestions").update({ status: "accepted", reviewed_at: new Date().toISOString() }).eq("id", id); await logAdminAuditEvent(sb, request, "admin.inbox.promote_to_source", { target_id: id, claim_source_id: sourceId }, id); return NextResponse.json({ success: true, claim_source_id: sourceId }); }
  if (action === "create_topic_candidate") { const title = String(body.title ?? `Inbox ${type} ${id.slice(0, 8)}`).trim().slice(0, 120); const slug = String(body.slug ?? (title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `inbox-${id}`)).slice(0, 160); const { data, error } = await sb.from("topic_candidates").insert({ title, slug, lang: body.lang ?? "en", country: body.country ?? "global", category: body.category ?? "general", source: "admin_created", contributor_hash: body.contributor_hash ?? null, why_people_ask_ai: `Created from admin inbox ${type}:${id}` }).select("id").single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); await logAdminAuditEvent(sb, request, "admin.inbox.create_topic_candidate", { target_id: id, topic_candidate_id: data.id }, id); return NextResponse.json({ success: true, topic_candidate_id: data.id }); }
  if (action === "link_to_claim") return NextResponse.json({ success: true, next: `/admin/verify-claim?claim_id=${encodeURIComponent(String(body.claim_id ?? ""))}` }); const status = statusFor(type, action); const updates: Record<string, string> = { status: status ?? "reviewing" }; if (type !== "community_post") updates.reviewed_at = new Date().toISOString(); const { error } = await sb.from(tableFor(type)).update(updates).eq("id", id); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); await logAdminAuditEvent(sb, request, "admin.inbox.update", { target_id: id, item_type: type, action, status: updates.status }, id); return NextResponse.json({ success: true, status: updates.status }); }
